// Generated by scripts/update-openai-pricing.mjs from https://models.dev/api.json.
// Do not edit manually.

export interface OpenAIModelPricing {
  inputPrice: number;
  outputPrice: number;
  cacheReadPrice?: number;
  cacheWritePrice?: number;
  tierThreshold?: number;
  inputPriceHigh?: number;
  outputPriceHigh?: number;
  cacheReadPriceHigh?: number;
  cacheWritePriceHigh?: number;
}

export const openAIModelPricing = {
  "gpt-3.5-turbo": {"inputPrice":0.5,"outputPrice":1.5,"cacheReadPrice":0},
  "gpt-4": {"inputPrice":30,"outputPrice":60},
  "gpt-4-turbo": {"inputPrice":10,"outputPrice":30},
  "gpt-4.1": {"inputPrice":2,"outputPrice":8,"cacheReadPrice":0.5},
  "gpt-4.1-mini": {"inputPrice":0.4,"outputPrice":1.6,"cacheReadPrice":0.1},
  "gpt-4.1-nano": {"inputPrice":0.1,"outputPrice":0.4,"cacheReadPrice":0.025},
  "gpt-4o": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-2024-05-13": {"inputPrice":5,"outputPrice":15},
  "gpt-4o-2024-08-06": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-2024-11-20": {"inputPrice":2.5,"outputPrice":10,"cacheReadPrice":1.25},
  "gpt-4o-mini": {"inputPrice":0.15,"outputPrice":0.6,"cacheReadPrice":0.075},
  "gpt-5": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5-chat-latest": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5-codex": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5-mini": {"inputPrice":0.25,"outputPrice":2,"cacheReadPrice":0.025},
  "gpt-5-nano": {"inputPrice":0.05,"outputPrice":0.4,"cacheReadPrice":0.005},
  "gpt-5-pro": {"inputPrice":15,"outputPrice":120},
  "gpt-5.1": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5.1-chat-latest": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5.1-codex": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5.1-codex-max": {"inputPrice":1.25,"outputPrice":10,"cacheReadPrice":0.125},
  "gpt-5.1-codex-mini": {"inputPrice":0.25,"outputPrice":2,"cacheReadPrice":0.025},
  "gpt-5.2": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.2-chat-latest": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.2-codex": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.2-pro": {"inputPrice":21,"outputPrice":168},
  "gpt-5.3-chat-latest": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.3-codex": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.3-codex-spark": {"inputPrice":1.75,"outputPrice":14,"cacheReadPrice":0.175},
  "gpt-5.4": {"inputPrice":2.5,"outputPrice":15,"cacheReadPrice":0.25,"tierThreshold":272000,"inputPriceHigh":5,"outputPriceHigh":22.5,"cacheReadPriceHigh":0.5},
  "gpt-5.4-mini": {"inputPrice":0.75,"outputPrice":4.5,"cacheReadPrice":0.075},
  "gpt-5.4-nano": {"inputPrice":0.2,"outputPrice":1.25,"cacheReadPrice":0.02},
  "gpt-5.4-pro": {"inputPrice":30,"outputPrice":180,"tierThreshold":272000,"inputPriceHigh":60,"outputPriceHigh":270},
  "gpt-5.5": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1},
  "gpt-5.5-pro": {"inputPrice":30,"outputPrice":180,"tierThreshold":272000,"inputPriceHigh":60,"outputPriceHigh":270},
  "gpt-5.6": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"cacheWritePrice":6.25,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1,"cacheWritePriceHigh":12.5},
  "gpt-5.6-luna": {"inputPrice":1,"outputPrice":6,"cacheReadPrice":0.1,"cacheWritePrice":1.25,"tierThreshold":272000,"inputPriceHigh":2,"outputPriceHigh":9,"cacheReadPriceHigh":0.2,"cacheWritePriceHigh":2.5},
  "gpt-5.6-sol": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":0.5,"cacheWritePrice":6.25,"tierThreshold":272000,"inputPriceHigh":10,"outputPriceHigh":45,"cacheReadPriceHigh":1,"cacheWritePriceHigh":12.5},
  "gpt-5.6-terra": {"inputPrice":2.5,"outputPrice":15,"cacheReadPrice":0.25,"cacheWritePrice":3.125,"tierThreshold":272000,"inputPriceHigh":5,"outputPriceHigh":22.5,"cacheReadPriceHigh":0.5,"cacheWritePriceHigh":6.25},
  "gpt-image-2": {"inputPrice":5,"outputPrice":30,"cacheReadPrice":1.25},
  "gpt-realtime-2.1": {"inputPrice":4,"outputPrice":24,"cacheReadPrice":0.4},
  "o1": {"inputPrice":15,"outputPrice":60,"cacheReadPrice":7.5},
  "o1-pro": {"inputPrice":150,"outputPrice":600},
  "o3": {"inputPrice":2,"outputPrice":8,"cacheReadPrice":0.5},
  "o3-deep-research": {"inputPrice":10,"outputPrice":40,"cacheReadPrice":2.5},
  "o3-mini": {"inputPrice":1.1,"outputPrice":4.4,"cacheReadPrice":0.55},
  "o3-pro": {"inputPrice":20,"outputPrice":80},
  "o4-mini": {"inputPrice":1.1,"outputPrice":4.4,"cacheReadPrice":0.275},
  "o4-mini-deep-research": {"inputPrice":2,"outputPrice":8,"cacheReadPrice":0.5},
  "text-embedding-3-large": {"inputPrice":0.13,"outputPrice":0},
  "text-embedding-3-small": {"inputPrice":0.02,"outputPrice":0},
  "text-embedding-ada-002": {"inputPrice":0.1,"outputPrice":0},
} satisfies Record<string, OpenAIModelPricing>;
